version: "3"
services:

    #Monitoreo, se usa air flow
    airflow-webserver:
        hostname: dacairflow
        container_name: airflow_container
        image: 'puckel/docker-airflow:1.10.9' 
        ports:
            - '8085:8080'
        networks:
            - datadac
        volumes:
            - airflow-data:/home/dlake/airflow/airflow/data
            - airflow-logs:/home/dlake/air/airflow/logs
            - ./airflow/dags:/usr/local/airflow/dags
            - ./airflow/requirements/requirements.txt:/requirements.txt
        restart: on-failure
        healthcheck:
            test: ["CMD", "curl", "-f", "http://myairflow:8080/admin/"]
            interval: 30s
            timeout: 20s
            retries: 3

    # zookeeper monitoreo
    zookeeper:
        hostname: daczookeeper
        container_name: zookeeper_container
        image: 'bitnami/zookeeper:3.7.0' 
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
        networks:
            - datadac
        restart: always

    # Nifi extraccion y transformacion de data
    nifi:
        hostname: dacnifi
        container_name: nifi_container
        image: 'apache/nifi:1.14.0'  
        ports:
            - '8091:8080'
        networks:
            - datadac
        volumes:
            - nifi-database_repository:/home/dlake/nifi/nifi-current/database_repository
            - nifi-flowfile_repository:/home/dlake/nifi-current/flowfile_repository
            - nifi-content_repository:/home/dlake/nifi/nifi-current/content_repository
            - nifi-provenance_repository:/home/dlake/nifi/nifi-current/provenance_repository
            - nifi-conf:/home/dlake/nifi/nifi-current/conf
            - nifi-state:/home/dlake/nifi/nifi-current/state
            - ./nifi/logs:/home/dlake/nifi/nifi-current/logs
            - ./nifi/jdbc:/home/dlake/nifi/nifi-current/jdbc
            - ./nifi/credentials:/home/dlake/nifi/nifi-current/credentials
        environment:
            - NIFI_WEB_HTTP_PORT=8080
            - NIFI_CLUSTER_IS_NODE=true
            - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
            - NIFI_ZK_CONNECT_STRING=myzookeeper:2181
            - NIFI_ELECTION_MAX_WAIT=30 sec
            - NIFI_SENSITIVE_PROPS_KEY='12345678901234567890A'
        restart: on-failure
        healthcheck:
            test: ["CMD", "curl", "-f", "http://mynifi:8080/nifi/"]
            interval: 30s
            timeout: 20s
            retries: 3

    # Flujos de Nifi
    registry:
        hostname: dacregistry
        container_name: registry_container
        image: 'apache/nifi-registry:1.15.0'  
        restart: on-failure
        ports:
            - "18080:18080"
        environment:
            - LOG_LEVEL=INFO
            - NIFI_REGISTRY_DB_DIR=/home/dlake/nifi-registry/nifi-registry-current/database
            - NIFI_REGISTRY_FLOW_PROVIDER=file
            - NIFI_REGISTRY_FLOW_STORAGE_DIR=/home/dlake/nifi-registry/nifi-registry-current/flow_storage
        volumes:
            - nifi_registry-database:/home/dlake/nifi-registry/nifi-registry-current/database
            - nifi_registry-flow_storage:/home/dlake/nifi-registry/nifi-registry-current/flow_storage
        networks:
            - datadac
        healthcheck:
            test: ["CMD", "curl", "-f", "http://myregistry:18080/nifi-registry/"]
            interval: 30s
            timeout: 20s
            retries: 3

    # base de datos
    postgres:
        hostname: dacpostgres
        container_name: postgres_container
        image: 'postgres:14-bullseye' 
        environment:
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'lapicero2'
            PGDATA: /home/dlake/data/postgres
        volumes:
            - postgres:/home/dlake/data/postgres
        ports:
            - "5432:5432"
        networks:
            - datadac
        restart: on-failure
        healthcheck:
            test: ["CMD", "pg_isready"]
            interval: 30s
            timeout: 20s
            retries: 3

    #base de datos
    pgadmin:
        hostname: dacpgadmin
        container_name: pgadmin_container
        image: 'dpage/pgadmin4:6.1'
        environment:
            PGADMIN_DEFAULT_EMAIL: 'rlavagnino@mp.gob.gt'
            PGADMIN_DEFAULT_PASSWORD: 'admin'
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            - pgadmin:/home/dlake/var/lib/pgadmin
        ports:
            - "5050:80"
        networks:
            - datadac
        restart: on-failure
        healthcheck:
            test: ["CMD", "curl", "-f", "http://mypgadmin:80/misc/ping"]
            interval: 30s
            timeout: 20s
            retries: 3

    # lake
    minio:
        hostname: dacminio
        container_name: minio_container
        image: 'bitnami/minio:2021' 
        environment:
            MINIO_ACCESS_KEY: minio_admin
            MINIO_SECRET_KEY: minio_password
        ports:
            - '9000:9000'
            - '9001:9001'
        volumes:
            - '/home/dlake/data:/data'
        networks:
            - datadac
        healthcheck:
            test: ["CMD", "curl", "-f", "http://myminio:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3

volumes:
    airflow-data:
    airflow-logs:
    nifi-database_repository:
    nifi-flowfile_repository:
    nifi-content_repository:
    nifi-provenance_repository:
    nifi-state:
    nifi-conf:
    nifi_registry-database:
    nifi_registry-flow_storage:
    postgres:
    pgadmin:

networks:
    datadac:
        driver: bridge
