apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: nifi
  name: nifi
spec:
  ports:
    - name: "8091"
      port: 8091
      targetPort: 8080
  selector:
    io.kompose.service: nifi
status:
  loadBalancer: {}
