apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.network/datadac: "true"
    io.kompose.service: pgadmin
  name: pgadmin
spec:
  containers:
    - env:
        - name: PGADMIN_CONFIG_SERVER_MODE
          value: "False"
        - name: PGADMIN_DEFAULT_EMAIL
          value: rlavagnino@mp.gob.gt
        - name: PGADMIN_DEFAULT_PASSWORD
          value: admin
      image: dpage/pgadmin4:6.1
      livenessProbe:
        httpGet:
          path: /misc/ping
          port: 80
        failureThreshold: 3
        periodSeconds: 60
        timeoutSeconds: 30
      name: pgadmin-container
      ports:
        - containerPort: 80
      resources: {}
      volumeMounts:
        - mountPath: /home/dlake/var/lib/pgadmin
          name: pgadmin
  hostname: dacpgadmin
  restartPolicy: OnFailure
  volumes:
    - name: pgadmin
      persistentVolumeClaim:
        claimName: pgadmin
status: {}
