apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.network/datadac: "true"
    io.kompose.service: postgres
  name: postgres
spec:
  containers:
    - env:
        - name: PGDATA
          value: /home/dlake/data/postgres
        - name: POSTGRES_PASSWORD
          value: lapicero2
        - name: POSTGRES_USER
          value: postgres
      image: postgres:14-bullseye
      livenessProbe:
        exec:
          command:
            - pg_isready
        failureThreshold: 3
        periodSeconds: 30
        timeoutSeconds: 20
      name: postgres-container
      ports:
        - containerPort: 5432
      resources: {}
      volumeMounts:
        - mountPath: /home/dlake/data/postgres
          name: postgres
  hostname: dacpostgres
  restartPolicy: OnFailure
  volumes:
    - name: postgres
      persistentVolumeClaim:
        claimName: postgres
status: {}
