apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: minio
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: minio
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/datadac: "true"
        io.kompose.service: minio
    spec:
      containers:
        - env:
            - name: MINIO_ACCESS_KEY
              value: minio_admin
            - name: MINIO_SECRET_KEY
              value: minio_password
          image: bitnami/minio:2021
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000                
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 20
          name: minio-container
          ports:
            - containerPort: 9000
            - containerPort: 9001
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: minio-claim0
      hostname: dacminio
      restartPolicy: Always
      volumes:
        - name: minio-claim0
          persistentVolumeClaim:
            claimName: minio-claim0
status: {}
