apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.network/datadac: "true"
    io.kompose.service: registry
  name: registry
spec:
  containers:
    - env:
        - name: LOG_LEVEL
          value: INFO
        - name: NIFI_REGISTRY_DB_DIR
          value: /home/dlake/nifi-registry/nifi-registry-current/database
        - name: NIFI_REGISTRY_FLOW_PROVIDER
          value: file
        - name: NIFI_REGISTRY_FLOW_STORAGE_DIR
          value: /home/dlake/nifi-registry/nifi-registry-current/flow_storage
      image: apache/nifi-registry:1.15.0
      livenessProbe:
        httpGet:
          path: /nifi-registry/
          port: 18080
        failureThreshold: 3
        periodSeconds: 30
        timeoutSeconds: 20
      name: registry-container
      ports:
        - containerPort: 18080
      resources: {}
      volumeMounts:
        - mountPath: /home/dlake/nifi-registry/nifi-registry-current/database
          name: nifi-registry-database
        - mountPath: /home/dlake/nifi-registry/nifi-registry-current/flow_storage
          name: nifi-registry-flow-storage
  hostname: dacregistry
  restartPolicy: OnFailure
  volumes:
    - name: nifi-registry-database
      persistentVolumeClaim:
        claimName: nifi-registry-database
    - name: nifi-registry-flow-storage
      persistentVolumeClaim:
        claimName: nifi-registry-flow-storage
status: {}
